### ISSUE TITLE
Usar factory_boy para generar datos de ejemplo

### ISSUE THREAD

**Issue by jantoniomartin** [jantoniomartin/hospitales-covid19#2]
Añadir factory_boy al proyecto para generar datos de ejemplo para los diferentes modelos, para facilitar la comprensión de la aplicación.

**Comment by jespino** [comment]
Ya lo tengo casi listo usando "sampledatahelper", si te parece bien.

**Comment by jantoniomartin** [comment]
Perfecto, muchísimas gracias.
